# File: backend/render.yaml
# Path: AchillesHeelOnline/backend/render.yaml
services:
  - type: web
    name: achilles-heel-chess-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    autoDeploy: true
    healthCheckPath: /